---
# based on https://github.com/phred/5minbootstrap/blob/master/bootstrap.yml
# pip install passlib для генерации хеша пароля
# python -c "from passlib.hash import sha256_crypt; import getpass; print sha256_crypt.encrypt(getpass.getpass())"

# usage: ansible-playbook -i hosts.ini -v 00_initial_setup.yml --user pi --ask-pass --ask-sudo-pass

- hosts: rasp_all
  vars:
    - pi_password: '$5$rounds=535000$iey7w7tUkDKMlx4v$/ahXsK.9hsoxHExPk1MMbXWtpfHGlEQh7travOSnwx4'
  handlers:
    - include: 'handlers/main.yml'

  tasks:
  - name: Check for pi_password
    fail:
      msg: "pi_password has not been defined"
    when: pi_password|default(False) == False

  - name: Add authorized pi key valia
    authorized_key: user=pi
                    key="{{ item }}"
    with_file:
      - files/ssh_keys/valia.pub

  - name: Add authorized pi key va
    authorized_key: user=pi
                    key="{{ item }}"
    with_file:
      - files/ssh_keys/va.pub

  # - name: Disallow password authentication
  #   action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  #   notify: Restart ssh

  - name: Change pi user
    user: name=pi password={{ pi_password }}
          generate_ssh_key=yes
    sudo: yes

  - name: Hostname | Update the hostname - hostname cmd
    hostname:
      name: "{{inventory_hostname_short}}"
    sudo: yes

  - name: Hostname | Update the hostname - (/etc/hostname)
    copy:
      content: "{{inventory_hostname_short}}{{'\n'}}"
      dest: /etc/hostname
      owner: root
      group: root
      mode: 0644
    sudo: yes

  - name: Hostname | Update the IPv4 hostname - (/etc/hosts)
    lineinfile:
      dest: /etc/hosts
      regexp: "^127.0.0.1"
      line: "127.0.0.1{{'\t'}}{{inventory_hostname}}{% if inventory_hostname != inventory_hostname_short %}{{'\t'}}{{inventory_hostname_short}}{% endif %}{{'\t'}}localhost"
      state: present
    notify: reboot
    sudo: yes




