---
# based on https://github.com/phred/5minbootstrap/blob/master/bootstrap.yml
# usage: ansible-playbook -i hosts.ini -v 01_update_and_basic_tools.yml --user pi
- hosts: rasp_all
  vars:
  handlers:
    - include: 'handlers/main.yml'

  tasks:

  - name: Uninstall the massive wolfram-alpha engine
    apt: pkg={{ item }} state=absent
    sudo: yes
    with_items:
      - wolfram-engine

  - name: Update APT package cache
    apt: update_cache=yes cache_valid_time=86400
    sudo: true

  - name: Run apt-get upgrade
    apt: upgrade=yes
    sudo: true

  - name: Make sure some basic tools are installed
    apt: pkg={{ item }} state=latest
    sudo: yes
    with_items:
      - git
      - tmux
      - curl
      - zsh
      - rpi-update
      - mc
      - screen

  - name: Autoremove any unused packages.
    shell: "apt-get autoremove --assume-yes --purge"
    sudo: yes

  - name: Let's Autoclean the system.
    shell: "apt-get autoclean --assume-yes"
    sudo: yes

  - name: Let's clean deb packages.
    shell: "apt-get clean"
    sudo: yes

  - shell: rpi-update
    sudo: true
    notify: reboot
